name: workloads-523
on:
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: ['9.0.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v5    

      - name: Setup .NET
        # uses: actions/setup-dotnet@v5
        uses: gowridurgad/setup-dotnet@523-feature
        with:
          dotnet-version: ${{ matrix.dotnet }}
          workloads: wasm-tools

      - name: Restore dependencies
        run: dotnet restore app/app.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore app/app.csproj

      - name: Pack
        run: dotnet pack --configuration Release --no-build app/app.csproj
      - name: Publish the package to nuget.org
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
           NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}



